// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use glib::object::Cast;
use glib::object::IsA;
use glib::signal::connect_raw;
use glib::signal::SignalHandlerId;
use glib::translate::*;
use glib::Value;
use glib_sys;
use gobject_sys;
use nm_sys;
use std::boxed::Box as Box_;
use std::fmt;
use std::mem::transmute;
#[cfg(any(feature = "v1_18", feature = "dox"))]
use BridgeVlan;
use Setting;

glib_wrapper! {
    pub struct SettingBridgePort(Object<nm_sys::NMSettingBridgePort, nm_sys::NMSettingBridgePortClass, SettingBridgePortClass>) @extends Setting;

    match fn {
        get_type => || nm_sys::nm_setting_bridge_port_get_type(),
    }
}

impl SettingBridgePort {
    /// Creates a new `SettingBridgePort` object with default values.
    ///
    /// # Returns
    ///
    /// the new empty `SettingBridgePort` object
    pub fn new() -> SettingBridgePort {
        unsafe { Setting::from_glib_full(nm_sys::nm_setting_bridge_port_new()).unsafe_cast() }
    }
}

impl Default for SettingBridgePort {
    fn default() -> Self {
        Self::new()
    }
}

pub const NONE_SETTING_BRIDGE_PORT: Option<&SettingBridgePort> = None;

/// Trait containing all `SettingBridgePort` methods.
///
/// # Implementors
///
/// [`SettingBridgePort`](struct.SettingBridgePort.html)
pub trait SettingBridgePortExt: 'static {
    /// Appends a new vlan and associated information to the setting. The
    /// given vlan gets sealed and a reference to it is added.
    ///
    /// Feature: `v1_18`
    ///
    /// ## `vlan`
    /// the vlan to add
    #[cfg(any(feature = "v1_18", feature = "dox"))]
    fn add_vlan(&self, vlan: &BridgeVlan);

    /// Removes all configured VLANs.
    ///
    /// Feature: `v1_18`
    ///
    #[cfg(any(feature = "v1_18", feature = "dox"))]
    fn clear_vlans(&self);

    ///
    /// # Returns
    ///
    /// the `SettingBridgePort:hairpin-mode` property of the setting
    fn get_hairpin_mode(&self) -> bool;

    ///
    /// Feature: `v1_18`
    ///
    ///
    /// # Returns
    ///
    /// the number of VLANs
    #[cfg(any(feature = "v1_18", feature = "dox"))]
    fn get_num_vlans(&self) -> u32;

    ///
    /// # Returns
    ///
    /// the `SettingBridgePort:path-cost` property of the setting
    fn get_path_cost(&self) -> u16;

    ///
    /// # Returns
    ///
    /// the `SettingBridgePort:priority` property of the setting
    fn get_priority(&self) -> u16;

    ///
    /// Feature: `v1_18`
    ///
    /// ## `idx`
    /// index number of the VLAN to return
    ///
    /// # Returns
    ///
    /// the VLAN at index `idx`
    #[cfg(any(feature = "v1_18", feature = "dox"))]
    fn get_vlan(&self, idx: u32) -> Option<BridgeVlan>;

    /// Removes the vlan at index `idx`.
    ///
    /// Feature: `v1_18`
    ///
    /// ## `idx`
    /// index number of the VLAN.
    #[cfg(any(feature = "v1_18", feature = "dox"))]
    fn remove_vlan(&self, idx: u32);

    /// Remove the VLAN with range `vid_start` to `vid_end`.
    /// If `vid_end` is zero, it is assumed to be equal to `vid_start`
    /// and so the single-id VLAN with id `vid_start` is removed.
    ///
    /// Feature: `v1_18`
    ///
    /// ## `vid_start`
    /// the vlan start index
    /// ## `vid_end`
    /// the vlan end index
    ///
    /// # Returns
    ///
    /// `true` if the vlan was found and removed; `false` otherwise
    #[cfg(any(feature = "v1_18", feature = "dox"))]
    fn remove_vlan_by_vid(&self, vid_start: u16, vid_end: u16) -> bool;

    /// Enables or disables "hairpin mode" for the port, which allows frames to
    /// be sent back out through the port the frame was received on.
    fn set_property_hairpin_mode(&self, hairpin_mode: bool);

    /// The Spanning Tree Protocol (STP) port cost for destinations via this
    /// port.
    fn set_property_path_cost(&self, path_cost: u32);

    /// The Spanning Tree Protocol (STP) priority of this bridge port.
    fn set_property_priority(&self, priority: u32);

    fn connect_property_hairpin_mode_notify<F: Fn(&Self) + 'static>(&self, f: F)
        -> SignalHandlerId;

    fn connect_property_path_cost_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    fn connect_property_priority_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;
}

impl<O: IsA<SettingBridgePort>> SettingBridgePortExt for O {
    #[cfg(any(feature = "v1_18", feature = "dox"))]
    fn add_vlan(&self, vlan: &BridgeVlan) {
        unsafe {
            nm_sys::nm_setting_bridge_port_add_vlan(
                self.as_ref().to_glib_none().0,
                vlan.to_glib_none().0,
            );
        }
    }

    #[cfg(any(feature = "v1_18", feature = "dox"))]
    fn clear_vlans(&self) {
        unsafe {
            nm_sys::nm_setting_bridge_port_clear_vlans(self.as_ref().to_glib_none().0);
        }
    }

    fn get_hairpin_mode(&self) -> bool {
        unsafe {
            from_glib(nm_sys::nm_setting_bridge_port_get_hairpin_mode(
                self.as_ref().to_glib_none().0,
            ))
        }
    }

    #[cfg(any(feature = "v1_18", feature = "dox"))]
    fn get_num_vlans(&self) -> u32 {
        unsafe { nm_sys::nm_setting_bridge_port_get_num_vlans(self.as_ref().to_glib_none().0) }
    }

    fn get_path_cost(&self) -> u16 {
        unsafe { nm_sys::nm_setting_bridge_port_get_path_cost(self.as_ref().to_glib_none().0) }
    }

    fn get_priority(&self) -> u16 {
        unsafe { nm_sys::nm_setting_bridge_port_get_priority(self.as_ref().to_glib_none().0) }
    }

    #[cfg(any(feature = "v1_18", feature = "dox"))]
    fn get_vlan(&self, idx: u32) -> Option<BridgeVlan> {
        unsafe {
            from_glib_none(nm_sys::nm_setting_bridge_port_get_vlan(
                self.as_ref().to_glib_none().0,
                idx,
            ))
        }
    }

    #[cfg(any(feature = "v1_18", feature = "dox"))]
    fn remove_vlan(&self, idx: u32) {
        unsafe {
            nm_sys::nm_setting_bridge_port_remove_vlan(self.as_ref().to_glib_none().0, idx);
        }
    }

    #[cfg(any(feature = "v1_18", feature = "dox"))]
    fn remove_vlan_by_vid(&self, vid_start: u16, vid_end: u16) -> bool {
        unsafe {
            from_glib(nm_sys::nm_setting_bridge_port_remove_vlan_by_vid(
                self.as_ref().to_glib_none().0,
                vid_start,
                vid_end,
            ))
        }
    }

    fn set_property_hairpin_mode(&self, hairpin_mode: bool) {
        unsafe {
            gobject_sys::g_object_set_property(
                self.to_glib_none().0 as *mut gobject_sys::GObject,
                b"hairpin-mode\0".as_ptr() as *const _,
                Value::from(&hairpin_mode).to_glib_none().0,
            );
        }
    }

    fn set_property_path_cost(&self, path_cost: u32) {
        unsafe {
            gobject_sys::g_object_set_property(
                self.to_glib_none().0 as *mut gobject_sys::GObject,
                b"path-cost\0".as_ptr() as *const _,
                Value::from(&path_cost).to_glib_none().0,
            );
        }
    }

    fn set_property_priority(&self, priority: u32) {
        unsafe {
            gobject_sys::g_object_set_property(
                self.to_glib_none().0 as *mut gobject_sys::GObject,
                b"priority\0".as_ptr() as *const _,
                Value::from(&priority).to_glib_none().0,
            );
        }
    }

    fn connect_property_hairpin_mode_notify<F: Fn(&Self) + 'static>(
        &self,
        f: F,
    ) -> SignalHandlerId {
        unsafe extern "C" fn notify_hairpin_mode_trampoline<P, F: Fn(&P) + 'static>(
            this: *mut nm_sys::NMSettingBridgePort,
            _param_spec: glib_sys::gpointer,
            f: glib_sys::gpointer,
        ) where
            P: IsA<SettingBridgePort>,
        {
            let f: &F = &*(f as *const F);
            f(&SettingBridgePort::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                b"notify::hairpin-mode\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(
                    notify_hairpin_mode_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    fn connect_property_path_cost_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_path_cost_trampoline<P, F: Fn(&P) + 'static>(
            this: *mut nm_sys::NMSettingBridgePort,
            _param_spec: glib_sys::gpointer,
            f: glib_sys::gpointer,
        ) where
            P: IsA<SettingBridgePort>,
        {
            let f: &F = &*(f as *const F);
            f(&SettingBridgePort::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                b"notify::path-cost\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(
                    notify_path_cost_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    fn connect_property_priority_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_priority_trampoline<P, F: Fn(&P) + 'static>(
            this: *mut nm_sys::NMSettingBridgePort,
            _param_spec: glib_sys::gpointer,
            f: glib_sys::gpointer,
        ) where
            P: IsA<SettingBridgePort>,
        {
            let f: &F = &*(f as *const F);
            f(&SettingBridgePort::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                b"notify::priority\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(
                    notify_priority_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }
}

impl fmt::Display for SettingBridgePort {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "SettingBridgePort")
    }
}
