// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

#[cfg(any(feature = "v1_16", feature = "dox"))]
use glib::object::Cast;
#[cfg(any(feature = "v1_16", feature = "dox"))]
use glib::object::ObjectType as ObjectType_;
#[cfg(any(feature = "v1_16", feature = "dox"))]
use glib::signal::connect_raw;
#[cfg(any(feature = "v1_16", feature = "dox"))]
use glib::signal::SignalHandlerId;
use glib::translate::*;
#[cfg(any(feature = "v1_16", feature = "dox"))]
use glib::GString;
#[cfg(any(feature = "v1_16", feature = "dox"))]
use glib::Value;
#[cfg(any(feature = "v1_16", feature = "dox"))]
use glib_sys;
#[cfg(any(feature = "v1_16", feature = "dox"))]
use gobject_sys;
use nm_sys;
#[cfg(any(feature = "v1_16", feature = "dox"))]
use std::boxed::Box as Box_;
use std::fmt;
#[cfg(any(feature = "v1_16", feature = "dox"))]
use std::mem;
#[cfg(any(feature = "v1_16", feature = "dox"))]
use std::mem::transmute;
use crate::Setting;
#[cfg(any(feature = "v1_16", feature = "dox"))]
use crate::SettingSecretFlags;
#[cfg(any(feature = "v1_20", feature = "dox"))]
use crate::Ternary;
#[cfg(any(feature = "v1_16", feature = "dox"))]
use crate::WireGuardPeer;

glib_wrapper! {
    pub struct SettingWireGuard(Object<nm_sys::NMSettingWireGuard, nm_sys::NMSettingWireGuardClass, SettingWireGuardClass>) @extends Setting;

    match fn {
        get_type => || nm_sys::nm_setting_wireguard_get_type(),
    }
}

impl SettingWireGuard {
    /// Creates a new `SettingWireGuard` object with default values.
    ///
    /// Feature: `v1_16`
    ///
    ///
    /// # Returns
    ///
    /// the new empty `SettingWireGuard` object
    #[cfg(any(feature = "v1_16", feature = "dox"))]
    pub fn new() -> SettingWireGuard {
        unsafe { Setting::from_glib_full(nm_sys::nm_setting_wireguard_new()).unsafe_cast() }
    }

    /// If a peer with the same public-key already exists, that
    /// one is replaced by `peer`. The new `peer` is always appended
    /// (or moved to) the end, so in case a peer is replaced, the
    /// indexes are shifted and the number of peers stays unchanged.
    ///
    /// Feature: `v1_16`
    ///
    /// ## `peer`
    /// the `WireGuardPeer` instance to append.
    ///  This seals `peer` and keeps a reference on the
    ///  instance.
    #[cfg(any(feature = "v1_16", feature = "dox"))]
    pub fn append_peer(&self, peer: &WireGuardPeer) {
        unsafe {
            nm_sys::nm_setting_wireguard_append_peer(self.to_glib_none().0, peer.to_glib_none().0);
        }
    }

    #[cfg(any(feature = "v1_16", feature = "dox"))]
    pub fn clear_peers(&self) -> u32 {
        unsafe { nm_sys::nm_setting_wireguard_clear_peers(self.to_glib_none().0) }
    }

    ///
    /// Feature: `v1_16`
    ///
    ///
    /// # Returns
    ///
    /// the set firewall mark.
    #[cfg(any(feature = "v1_16", feature = "dox"))]
    pub fn get_fwmark(&self) -> u32 {
        unsafe { nm_sys::nm_setting_wireguard_get_fwmark(self.to_glib_none().0) }
    }

    ///
    /// Feature: `v1_20`
    ///
    ///
    /// # Returns
    ///
    /// the "ip4-auto-default-route" property of the setting.
    #[cfg(any(feature = "v1_20", feature = "dox"))]
    pub fn get_ip4_auto_default_route(&self) -> Ternary {
        unsafe {
            from_glib(nm_sys::nm_setting_wireguard_get_ip4_auto_default_route(
                self.to_glib_none().0,
            ))
        }
    }

    ///
    /// Feature: `v1_20`
    ///
    ///
    /// # Returns
    ///
    /// the "ip6-auto-default-route" property of the setting.
    #[cfg(any(feature = "v1_20", feature = "dox"))]
    pub fn get_ip6_auto_default_route(&self) -> Ternary {
        unsafe {
            from_glib(nm_sys::nm_setting_wireguard_get_ip6_auto_default_route(
                self.to_glib_none().0,
            ))
        }
    }

    ///
    /// Feature: `v1_16`
    ///
    ///
    /// # Returns
    ///
    /// the set UDP listen port.
    #[cfg(any(feature = "v1_16", feature = "dox"))]
    pub fn get_listen_port(&self) -> u16 {
        unsafe { nm_sys::nm_setting_wireguard_get_listen_port(self.to_glib_none().0) }
    }

    ///
    /// Feature: `v1_16`
    ///
    ///
    /// # Returns
    ///
    /// the MTU of the setting.
    #[cfg(any(feature = "v1_16", feature = "dox"))]
    pub fn get_mtu(&self) -> u32 {
        unsafe { nm_sys::nm_setting_wireguard_get_mtu(self.to_glib_none().0) }
    }

    ///
    /// Feature: `v1_16`
    ///
    /// ## `idx`
    /// the index to lookup.
    ///
    /// # Returns
    ///
    /// the `WireGuardPeer` entry at
    ///  index `idx`. If the index is out of range, `None` is returned.
    #[cfg(any(feature = "v1_16", feature = "dox"))]
    pub fn get_peer(&self, idx: u32) -> Option<WireGuardPeer> {
        unsafe {
            from_glib_none(nm_sys::nm_setting_wireguard_get_peer(
                self.to_glib_none().0,
                idx,
            ))
        }
    }

    ///
    /// Feature: `v1_16`
    ///
    /// ## `public_key`
    /// the public key for looking up the
    ///  peer.
    /// ## `out_idx`
    /// optional output argument
    ///  for the index of the found peer. If no index is found,
    ///  this is set to the `SettingWireGuard::get_peers_len`.
    ///
    /// # Returns
    ///
    /// the `WireGuardPeer` instance with a
    ///  matching public key. If no such peer exists, `None` is returned.
    #[cfg(any(feature = "v1_16", feature = "dox"))]
    pub fn get_peer_by_public_key(&self, public_key: &str) -> (WireGuardPeer, u32) {
        unsafe {
            let mut out_idx = mem::MaybeUninit::uninit();
            let ret = from_glib_none(nm_sys::nm_setting_wireguard_get_peer_by_public_key(
                self.to_glib_none().0,
                public_key.to_glib_none().0,
                out_idx.as_mut_ptr(),
            ));
            let out_idx = out_idx.assume_init();
            (ret, out_idx)
        }
    }

    ///
    /// Feature: `v1_16`
    ///
    ///
    /// # Returns
    ///
    /// whether automatically add peer routes.
    #[cfg(any(feature = "v1_16", feature = "dox"))]
    pub fn get_peer_routes(&self) -> bool {
        unsafe {
            from_glib(nm_sys::nm_setting_wireguard_get_peer_routes(
                self.to_glib_none().0,
            ))
        }
    }

    ///
    /// Feature: `v1_16`
    ///
    ///
    /// # Returns
    ///
    /// the number of registered peers.
    #[cfg(any(feature = "v1_16", feature = "dox"))]
    pub fn get_peers_len(&self) -> u32 {
        unsafe { nm_sys::nm_setting_wireguard_get_peers_len(self.to_glib_none().0) }
    }

    ///
    /// Feature: `v1_16`
    ///
    ///
    /// # Returns
    ///
    /// the set private-key or `None`.
    #[cfg(any(feature = "v1_16", feature = "dox"))]
    pub fn get_private_key(&self) -> Option<GString> {
        unsafe {
            from_glib_none(nm_sys::nm_setting_wireguard_get_private_key(
                self.to_glib_none().0,
            ))
        }
    }

    ///
    /// Feature: `v1_16`
    ///
    ///
    /// # Returns
    ///
    /// the secret-flags for `SettingWireGuard:private-key`.
    #[cfg(any(feature = "v1_16", feature = "dox"))]
    pub fn get_private_key_flags(&self) -> SettingSecretFlags {
        unsafe {
            from_glib(nm_sys::nm_setting_wireguard_get_private_key_flags(
                self.to_glib_none().0,
            ))
        }
    }

    ///
    /// Feature: `v1_16`
    ///
    /// ## `idx`
    /// the index to remove.
    ///
    /// # Returns
    ///
    /// `true` if `idx` was in range and a peer
    ///  was removed. Otherwise, `self` is unchanged.
    #[cfg(any(feature = "v1_16", feature = "dox"))]
    pub fn remove_peer(&self, idx: u32) -> bool {
        unsafe {
            from_glib(nm_sys::nm_setting_wireguard_remove_peer(
                self.to_glib_none().0,
                idx,
            ))
        }
    }

    /// If `idx` is one past the last peer, the behavior is the same
    /// as `SettingWireGuard::append_peer`.
    /// Otherwise, the peer will be at `idx` and replace the peer
    /// instance at that index. Note that if a peer with the same
    /// public-key exists on another index, then that peer will also
    /// be replaced. In that case, the number of peers will shrink
    /// by one (because the one at `idx` got replace and then one
    /// with the same public-key got removed). This also means,
    /// that the resulting index afterwards may be one less than
    /// `idx` (if another peer with a lower index was dropped).
    ///
    /// Feature: `v1_16`
    ///
    /// ## `peer`
    /// the `WireGuardPeer` instance to set.
    ///  This seals `peer` and keeps a reference on the
    ///  instance.
    /// ## `idx`
    /// the index, in the range of 0 to the number of
    ///  peers (including). That means, if `idx` is one past
    ///  the end of the number of peers, this is the same as
    ///  `SettingWireGuard::append_peer`. Otherwise, the
    ///  peer at this index is replaced.
    #[cfg(any(feature = "v1_16", feature = "dox"))]
    pub fn set_peer(&self, peer: &WireGuardPeer, idx: u32) {
        unsafe {
            nm_sys::nm_setting_wireguard_set_peer(
                self.to_glib_none().0,
                peer.to_glib_none().0,
                idx,
            );
        }
    }

    /// The use of fwmark is optional and is by default off. Setting it to 0
    /// disables it. Otherwise it is a 32-bit fwmark for outgoing packets.
    ///
    /// Note that "ip4-auto-default-route" or "ip6-auto-default-route" enabled,
    /// implies to automatically choose a fwmark.
    ///
    /// Feature: `v1_16`
    ///
    #[cfg(any(feature = "v1_16", feature = "dox"))]
    pub fn set_property_fwmark(&self, fwmark: u32) {
        unsafe {
            gobject_sys::g_object_set_property(
                self.as_ptr() as *mut gobject_sys::GObject,
                b"fwmark\0".as_ptr() as *const _,
                Value::from(&fwmark).to_glib_none().0,
            );
        }
    }

    /// Whether to enable special handling of the IPv4 default route.
    /// If enabled, the IPv4 default route from wireguard.peer-routes
    /// will be placed to a dedicated routing-table and two policy routing rules
    /// will be added. The fwmark number is also used as routing-table for the default-route,
    /// and if fwmark is zero, an unused fwmark/table is chosen automatically.
    /// This corresponds to what wg-quick does with Table=auto and what WireGuard
    /// calls "Improved Rule-based Routing".
    ///
    /// Note that for this automatism to work, you usually don't want to set
    /// ipv4.gateway, because that will result in a conflicting default route.
    ///
    /// Leaving this at the default will enable this option automatically
    /// if ipv4.never-default is not set and there are any peers that use
    /// a default-route as allowed-ips.
    ///
    /// Feature: `v1_20`
    ///
    #[cfg(any(feature = "v1_20", feature = "dox"))]
    pub fn set_property_ip4_auto_default_route(&self, ip4_auto_default_route: Ternary) {
        unsafe {
            gobject_sys::g_object_set_property(
                self.as_ptr() as *mut gobject_sys::GObject,
                b"ip4-auto-default-route\0".as_ptr() as *const _,
                Value::from(&ip4_auto_default_route).to_glib_none().0,
            );
        }
    }

    /// Like ip4-auto-default-route, but for the IPv6 default route.
    ///
    /// Feature: `v1_20`
    ///
    #[cfg(any(feature = "v1_20", feature = "dox"))]
    pub fn set_property_ip6_auto_default_route(&self, ip6_auto_default_route: Ternary) {
        unsafe {
            gobject_sys::g_object_set_property(
                self.as_ptr() as *mut gobject_sys::GObject,
                b"ip6-auto-default-route\0".as_ptr() as *const _,
                Value::from(&ip6_auto_default_route).to_glib_none().0,
            );
        }
    }

    /// The listen-port. If listen-port is not specified, the port will be chosen
    /// randomly when the interface comes up.
    ///
    /// Feature: `v1_16`
    ///
    #[cfg(any(feature = "v1_16", feature = "dox"))]
    pub fn set_property_listen_port(&self, listen_port: u32) {
        unsafe {
            gobject_sys::g_object_set_property(
                self.as_ptr() as *mut gobject_sys::GObject,
                b"listen-port\0".as_ptr() as *const _,
                Value::from(&listen_port).to_glib_none().0,
            );
        }
    }

    /// If non-zero, only transmit packets of the specified size or smaller,
    /// breaking larger packets up into multiple fragments.
    ///
    /// If zero a default MTU is used. Note that contrary to wg-quick's MTU
    /// setting, this does not take into account the current routes at the
    /// time of activation.
    ///
    /// Feature: `v1_16`
    ///
    #[cfg(any(feature = "v1_16", feature = "dox"))]
    pub fn set_property_mtu(&self, mtu: u32) {
        unsafe {
            gobject_sys::g_object_set_property(
                self.as_ptr() as *mut gobject_sys::GObject,
                b"mtu\0".as_ptr() as *const _,
                Value::from(&mtu).to_glib_none().0,
            );
        }
    }

    /// Whether to automatically add routes for the AllowedIPs ranges
    /// of the peers. If `true` (the default), NetworkManager will automatically
    /// add routes in the routing tables according to ipv4.route-table and
    /// ipv6.route-table. Usually you want this automatism enabled.
    /// If `false`, no such routes are added automatically. In this case, the
    /// user may want to configure static routes in ipv4.routes and ipv6.routes,
    /// respectively.
    ///
    /// Note that if the peer's AllowedIPs is "0.0.0.0/0" or "::/0" and the profile's
    /// ipv4.never-default or ipv6.never-default setting is enabled, the peer route for
    /// this peer won't be added automatically.
    ///
    /// Feature: `v1_16`
    ///
    #[cfg(any(feature = "v1_16", feature = "dox"))]
    pub fn set_property_peer_routes(&self, peer_routes: bool) {
        unsafe {
            gobject_sys::g_object_set_property(
                self.as_ptr() as *mut gobject_sys::GObject,
                b"peer-routes\0".as_ptr() as *const _,
                Value::from(&peer_routes).to_glib_none().0,
            );
        }
    }

    /// The 256 bit private-key in base64 encoding.
    ///
    /// Feature: `v1_16`
    ///
    #[cfg(any(feature = "v1_16", feature = "dox"))]
    pub fn set_property_private_key(&self, private_key: Option<&str>) {
        unsafe {
            gobject_sys::g_object_set_property(
                self.as_ptr() as *mut gobject_sys::GObject,
                b"private-key\0".as_ptr() as *const _,
                Value::from(private_key).to_glib_none().0,
            );
        }
    }

    /// Flags indicating how to handle the `SettingWirelessSecurity:private-key`
    /// property.
    ///
    /// Feature: `v1_16`
    ///
    #[cfg(any(feature = "v1_16", feature = "dox"))]
    pub fn set_property_private_key_flags(&self, private_key_flags: SettingSecretFlags) {
        unsafe {
            gobject_sys::g_object_set_property(
                self.as_ptr() as *mut gobject_sys::GObject,
                b"private-key-flags\0".as_ptr() as *const _,
                Value::from(&private_key_flags).to_glib_none().0,
            );
        }
    }

    #[cfg(any(feature = "v1_16", feature = "dox"))]
    pub fn connect_property_fwmark_notify<F: Fn(&SettingWireGuard) + 'static>(
        &self,
        f: F,
    ) -> SignalHandlerId {
        unsafe extern "C" fn notify_fwmark_trampoline<F: Fn(&SettingWireGuard) + 'static>(
            this: *mut nm_sys::NMSettingWireGuard,
            _param_spec: glib_sys::gpointer,
            f: glib_sys::gpointer,
        ) {
            let f: &F = &*(f as *const F);
            f(&from_glib_borrow(this))
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                b"notify::fwmark\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(
                    notify_fwmark_trampoline::<F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[cfg(any(feature = "v1_20", feature = "dox"))]
    pub fn connect_property_ip4_auto_default_route_notify<F: Fn(&SettingWireGuard) + 'static>(
        &self,
        f: F,
    ) -> SignalHandlerId {
        unsafe extern "C" fn notify_ip4_auto_default_route_trampoline<
            F: Fn(&SettingWireGuard) + 'static,
        >(
            this: *mut nm_sys::NMSettingWireGuard,
            _param_spec: glib_sys::gpointer,
            f: glib_sys::gpointer,
        ) {
            let f: &F = &*(f as *const F);
            f(&from_glib_borrow(this))
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                b"notify::ip4-auto-default-route\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(
                    notify_ip4_auto_default_route_trampoline::<F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[cfg(any(feature = "v1_20", feature = "dox"))]
    pub fn connect_property_ip6_auto_default_route_notify<F: Fn(&SettingWireGuard) + 'static>(
        &self,
        f: F,
    ) -> SignalHandlerId {
        unsafe extern "C" fn notify_ip6_auto_default_route_trampoline<
            F: Fn(&SettingWireGuard) + 'static,
        >(
            this: *mut nm_sys::NMSettingWireGuard,
            _param_spec: glib_sys::gpointer,
            f: glib_sys::gpointer,
        ) {
            let f: &F = &*(f as *const F);
            f(&from_glib_borrow(this))
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                b"notify::ip6-auto-default-route\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(
                    notify_ip6_auto_default_route_trampoline::<F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[cfg(any(feature = "v1_16", feature = "dox"))]
    pub fn connect_property_listen_port_notify<F: Fn(&SettingWireGuard) + 'static>(
        &self,
        f: F,
    ) -> SignalHandlerId {
        unsafe extern "C" fn notify_listen_port_trampoline<F: Fn(&SettingWireGuard) + 'static>(
            this: *mut nm_sys::NMSettingWireGuard,
            _param_spec: glib_sys::gpointer,
            f: glib_sys::gpointer,
        ) {
            let f: &F = &*(f as *const F);
            f(&from_glib_borrow(this))
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                b"notify::listen-port\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(
                    notify_listen_port_trampoline::<F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[cfg(any(feature = "v1_16", feature = "dox"))]
    pub fn connect_property_mtu_notify<F: Fn(&SettingWireGuard) + 'static>(
        &self,
        f: F,
    ) -> SignalHandlerId {
        unsafe extern "C" fn notify_mtu_trampoline<F: Fn(&SettingWireGuard) + 'static>(
            this: *mut nm_sys::NMSettingWireGuard,
            _param_spec: glib_sys::gpointer,
            f: glib_sys::gpointer,
        ) {
            let f: &F = &*(f as *const F);
            f(&from_glib_borrow(this))
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                b"notify::mtu\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(
                    notify_mtu_trampoline::<F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[cfg(any(feature = "v1_16", feature = "dox"))]
    pub fn connect_property_peer_routes_notify<F: Fn(&SettingWireGuard) + 'static>(
        &self,
        f: F,
    ) -> SignalHandlerId {
        unsafe extern "C" fn notify_peer_routes_trampoline<F: Fn(&SettingWireGuard) + 'static>(
            this: *mut nm_sys::NMSettingWireGuard,
            _param_spec: glib_sys::gpointer,
            f: glib_sys::gpointer,
        ) {
            let f: &F = &*(f as *const F);
            f(&from_glib_borrow(this))
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                b"notify::peer-routes\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(
                    notify_peer_routes_trampoline::<F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[cfg(any(feature = "v1_16", feature = "dox"))]
    pub fn connect_property_private_key_notify<F: Fn(&SettingWireGuard) + 'static>(
        &self,
        f: F,
    ) -> SignalHandlerId {
        unsafe extern "C" fn notify_private_key_trampoline<F: Fn(&SettingWireGuard) + 'static>(
            this: *mut nm_sys::NMSettingWireGuard,
            _param_spec: glib_sys::gpointer,
            f: glib_sys::gpointer,
        ) {
            let f: &F = &*(f as *const F);
            f(&from_glib_borrow(this))
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                b"notify::private-key\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(
                    notify_private_key_trampoline::<F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[cfg(any(feature = "v1_16", feature = "dox"))]
    pub fn connect_property_private_key_flags_notify<F: Fn(&SettingWireGuard) + 'static>(
        &self,
        f: F,
    ) -> SignalHandlerId {
        unsafe extern "C" fn notify_private_key_flags_trampoline<
            F: Fn(&SettingWireGuard) + 'static,
        >(
            this: *mut nm_sys::NMSettingWireGuard,
            _param_spec: glib_sys::gpointer,
            f: glib_sys::gpointer,
        ) {
            let f: &F = &*(f as *const F);
            f(&from_glib_borrow(this))
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                b"notify::private-key-flags\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(
                    notify_private_key_flags_trampoline::<F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }
}

#[cfg(any(feature = "v1_16", feature = "dox"))]
impl Default for SettingWireGuard {
    fn default() -> Self {
        Self::new()
    }
}

impl fmt::Display for SettingWireGuard {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "SettingWireGuard")
    }
}
